from enum import IntEnum, unique

__all__ = (
	'DALICommand',
	'DeviceType',
	'DALILEDCommand',
)

@unique
class DALICommand(IntEnum):
	lampOff = 0,
	fadeUp = 1,
	fadeDown = 2,
	stepUp = 3,
	stepDown = 4,
	gotoMax = 5,
	gotoMin = 6,
	stepDownAndOff = 7,
	stepUpAndOn = 8,
	enableDirectCtrl = 9,
	gotoScene = 10,
	reset = 11,
	levelToDTR = 12,
	dtrToMaxLevel = 13,
	dtrToMinLevel = 14,
	dtrToSysFailLevel = 15,
	dtrToOnLevel = 16,
	dtrToFadeTime = 17,
	dtrToFadeRate = 18,
	dtrToScene = 19,
	removeFromScene = 20,
	addToGroup = 21,
	removeFromGroup = 22,
	dtrToShortAddress = 23,
	enableMemoryWrite = 24,
	queryStatus = 25,
	queryControlGear = 26,
	queryFailure = 27,
	queryPowerOn = 28,
	queryLimitError = 29,
	queryResetState = 30,
	queryMissingShortAddr = 31,
	queryVersionNumber = 32,
	queryDTR = 33,
	queryDeviceType = 34,
	queryPhyMinLevel = 35,
	queryPowerFailure = 36,
	queryDTR1 = 37,
	queryDTR2 = 38,
	queryLevel = 39,
	queryMaxLevel = 40,
	queryMinLevel = 41,
	queryOnLevel = 42,
	queryFailureLevel = 43,
	queryFadeTimeRate = 44,
	querySceneLevel = 45,
	queryGroups0_7 = 46,
	queryGroups8_15 = 47,
	queryRandomAddrH = 48,
	queryRandomAddrM = 49,
	queryRandomAddrL = 50,
	readMemoryLoc = 51,
	deviceSpecific = 52,
	nop = 53,

@unique
class DeviceType(IntEnum):
	led = 6

@unique
class DALILEDCommand(IntEnum):
	referenceSystemPower = 0,
	enableCurrentProt = 1,
	disableCurrentProt = 2,
	selectCurve = 3,
	dtrToFastFadeTime = 4,
	queryGearType = 5,
	queryDimmingCurve = 6,
	queryOperatingModes = 7,
	queryFeatures = 8,
	queryFailStatus = 9,
	queryShortCircuit = 10,
	queryOpenCircuit = 11,
	queryLoadDecrease = 12,
	queryLoadIncrease = 13,
	queryCurrentProtActive = 14,
	queryThermalShutDown = 15,
	queryThermalOverload = 16,
	queryReferenceRunning = 17,
	queryReferenceFailed = 18,
	queryCurrentProtEn = 19,
	queryOperatingMode = 20,
	queryFastFadeTime = 21,
	queryMinFastFadeTime = 22,
	queryExtVersionNumber = 23,
	nop = 24,
